# Generated by Django 5.1 on 2024-09-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_contact_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=122)),
                ('sellername', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('bookprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('info', models.TextField()),
            ],
        ),
    ]
