# Generated by Django 5.1.1 on 2024-11-15 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_sell'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='book_images/'),
        ),
    ]
