# Generated by Django 5.1 on 2025-03-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_available_for_rent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
